[workspace]
authors = ["Feiran (Alex) Qin"]
channels = ["conda-forge"]
name = "FlashFuzz"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.12"
tqdm = ">=4.67.1,<5"
types-tqdm = ">=4.67.0.20250516,<5"
