[workspace]
authors = ["canarypwn <canarypwn@aosc.io>"]
channels = ["conda-forge"]
name = "torch_cpu"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.12"
anthropic = ">=0.66.0,<0.67"
numpy = ">=2.3.2,<3"
google-genai = ">=1.52.0,<2"

[pypi-dependencies]
torch = "==2.7.0"
requests = ">=2.31,<3"
