[workspace]
authors = ["canarypwn <canarypwn@aosc.io>"]
channels = ["conda-forge"]
name = "tf_cpu"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.10"
tensorflow = "==2.16.1"

[pypi-dependencies]
google-generativeai = ">=0.8.3"
requests = ">=2.31,<3"
