[workspace]
authors = ["canarypwn <canarypwn@aosc.io>"]
channels = ["conda-forge"]
name = "tf"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.10"
tensorflow = "==2.16.1"
anthropic = ">=0.66.0,<0.67"
